# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

import os
import yaml
from detectron2.config import CfgNode as CN


def add_dataset_config(cfg):
    _C = cfg
    _C.DATASETS = CN()
    # List of the dataset names for training, as present in paths_catalog.py
    _C.DATASETS.TRAIN = ()
    # List of the dataset names for testing, as present in paths_catalog.py
    _C.DATASETS.TEST = ()

    _C.DATASETS.RATIOS = []

    _C.DATASETS.AUG = False
    _C.DATASETS.RANDOM_CROP_PROB = 0.0
    _C.DATASETS.IGNORE_DIFFICULT = False
    _C.DATASETS.FIX_CROP = False
    _C.DATASETS.CROP_SIZE = (512, 512)
    _C.DATASETS.MAX_ROTATE_THETA = 30
    _C.DATASETS.FIX_ROTATE = False

def add_glass_config(cfg):
    """
    Add config for Hybrid head.
    """
    ## Orientation related fields
    cfg.MODEL.ROTATED_BOXES_ON = False
    cfg.MODEL.ORIENTATION_ON = False

    ## Localization old Hybrid head config
    cfg.MODEL.ROI_HYBRID_HEAD = CN()
    cfg.MODEL.ROI_HYBRID_HEAD.NAME = "ResBlockHybridHead"
    cfg.MODEL.ROI_HYBRID_HEAD.POOLER_RESOLUTION = 64
    cfg.MODEL.ROI_HYBRID_HEAD.NUM_FEATURES = 256
    cfg.MODEL.ROI_HYBRID_HEAD.DEPTH = 3
    cfg.MODEL.ROI_HYBRID_HEAD.NORM_IMG_CROPS = False
    ## Filter dont care boxes in the RPN not recommended to use untested yet
    cfg.MODEL.FILTERED_RPN = CN()
    cfg.MODEL.FILTERED_RPN.IGNORE_TEXT = ["###", ""]

    cfg.TEST.USE_FILTERED_METRICS = True

    ## E2E Feature Fusion
    cfg.MODEL.LOCAL_FEATURE_EXTRACTOR = CN()
    cfg.MODEL.LOCAL_FEATURE_EXTRACTOR.NAME = "ResNet_FeatureExtractor"
    cfg.MODEL.LOCAL_FEATURE_EXTRACTOR.NUM_FEATURES = 256

    cfg.MODEL.HYBRID_FUSION = CN()
    cfg.MODEL.HYBRID_FUSION.NAME = "MultiAspectGCAttention"
    cfg.MODEL.HYBRID_FUSION.NUM_FEATURES = 256

    ## MultiAspectGCAttention
    cfg.MODEL.HYBRID_FUSION.RATIO = 0.5
    cfg.MODEL.HYBRID_FUSION.HEADERS = 8
    cfg.MODEL.HYBRID_FUSION.FUSION_TYPE = 'channel_add'
    cfg.MODEL.ROI_MASK_HEAD.LOSS_WEIGHT = 0.005
    cfg.MODEL.ROI_HEADS.CLASS_NAMES = ['word']
    cfg.MODEL.ROI_ORIENTATION_HEAD = CN()
    cfg.MODEL.ROI_ORIENTATION_HEAD.LOSS_WEIGHT = 1.0
    cfg.MODEL.ROI_ORIENTATION_HEAD.APPLY_TO_BOXES = False
    cfg.MODEL.ROI_ORIENTATION_HEAD.APPLY_TO_BOXES_DURING_TRAINING = True


    # cfg.MODEL.ROI_MASK_HEAD.MASK_INFERENCE = True

    # cfg.TEST.MIN_SIZE_TEST = 1600
    # cfg.TEST.MIN_SIZE_TEST = 1600
    cfg.INPUT.MIN_SIZE_TEST = 1600
    cfg.INPUT.MAX_SIZE_TEST = 1600


    cfg.INPUT.ROTATION = CN()
    cfg.INPUT.ROTATION.ENABLED = False
    cfg.INPUT.ROTATION.ANGLES = [0]


def add_e2e_config(cfg):
    """
    Add config for cotrain.
    """
    _C = cfg
    _C.MODEL.RECOGNIZER_ON = True
    _C.MODEL.ROI_MASK_HEAD.SAMPLE_WORDS_STRATEGY = 'random'  # 'random' | 'long_first'
    _C.MODEL.ROI_MASK_HEAD.SAMPLE_WORDS_STRATEGY_PROB = 0.3

    _C.MODEL.ROI_MASK_HEAD.SENSITIVE = True

    _C.MODEL.ROI_MASK_HEAD.RECOGNIZER_HEAD = CN()

    _C.MODEL.ROI_MASK_HEAD.RECOGNIZER_HEAD.POOLER_PAD = CN()
    _C.MODEL.ROI_MASK_HEAD.RECOGNIZER_HEAD.POOLER_PAD.NAME = ""

    _C.MODEL.ROI_MASK_HEAD.RECOGNIZER_HEAD.BACKBONE = CN()
    _C.MODEL.ROI_MASK_HEAD.RECOGNIZER_HEAD.BACKBONE.NAME = "CNN_V1"

    _C.MODEL.ROI_MASK_HEAD.RECOGNIZER_HEAD.ENCODER = CN()
    _C.MODEL.ROI_MASK_HEAD.RECOGNIZER_HEAD.ENCODER.NAME = "BiLSTMBlock"  # | TransformerEncoderBlock
    _C.MODEL.ROI_MASK_HEAD.RECOGNIZER_HEAD.ENCODER.NUM_OF_LAYERS = 2
    _C.MODEL.ROI_MASK_HEAD.RECOGNIZER_HEAD.ENCODER.HEIGHT_REDUCTION = "mean"  # "flatten" | "mean"
    _C.MODEL.ROI_MASK_HEAD.RECOGNIZER_HEAD.ENCODER.N_HEAD = 8  # for TransformerEncoderBlock (multi-attention heads)

    _C.MODEL.ROI_MASK_HEAD.RECOGNIZER_HEAD.DECODER = CN()
    _C.MODEL.ROI_MASK_HEAD.RECOGNIZER_HEAD.DECODER.NAME = "ASTER"
    _C.MODEL.ROI_MASK_HEAD.RECOGNIZER_HEAD.DECODER.POS_ENC_HEIGHT_WIDTH = None

    ################# config duplication #################
    _C.MODEL.ROI_RECOGNIZER_HEAD = CN()
    _C.MODEL.ROI_RECOGNIZER_HEAD.SAMPLE_WORDS_STRATEGY = 'random'  # 'random' | 'long_first'
    _C.MODEL.ROI_RECOGNIZER_HEAD.SAMPLE_WORDS_STRATEGY_PROB = 0.3

    _C.MODEL.ROI_RECOGNIZER_HEAD.NAME = ""
    _C.MODEL.ROI_RECOGNIZER_HEAD.RECOGNIZER_HEAD = CN()

    _C.MODEL.ROI_RECOGNIZER_HEAD.RECOGNIZER_HEAD.POOLER_PAD = CN()
    _C.MODEL.ROI_RECOGNIZER_HEAD.RECOGNIZER_HEAD.POOLER_PAD.NAME = ""

    _C.MODEL.ROI_RECOGNIZER_HEAD.LABELS_TYPE = "attention"
    _C.MODEL.ROI_RECOGNIZER_HEAD.MAX_WORD_LENGTH = 50
    _C.MODEL.ROI_RECOGNIZER_HEAD.CHARACTER_SET = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~ '
    _C.MODEL.ROI_RECOGNIZER_HEAD.UNK_SYMBOL_PRED = False
    _C.MODEL.ROI_RECOGNIZER_HEAD.IGNORE_EMPTY_TEXT = True
    _C.MODEL.ROI_RECOGNIZER_HEAD.POOLER_RESOLUTION_WIDTH = 32
    _C.MODEL.ROI_RECOGNIZER_HEAD.POOLER_RESOLUTION_HEIGHT = 32
    _C.MODEL.ROI_RECOGNIZER_HEAD.IN_FEATURES = ['p2', 'p3', 'p4', 'p5', 'p6']
    _C.MODEL.ROI_RECOGNIZER_HEAD.CLASS_IND = 0
    _C.MODEL.ROI_RECOGNIZER_HEAD.PAD_SAMPLER = ''  # 'FeatPadV1' 'FeatPadV2'
    _C.MODEL.ROI_RECOGNIZER_HEAD.MAX_BATCH_SIZE = 256
    _C.MODEL.ROI_RECOGNIZER_HEAD.LOSS_WEIGHT = 2.0
    _C.MODEL.ROI_RECOGNIZER_HEAD.IGNORE_TEXT = ["###"]
    _C.MODEL.ROI_RECOGNIZER_HEAD.SENSITIVE = True  # sensitive character mode

    _C.MODEL.ROI_RECOGNIZER_HEAD.POOLER_TYPE = "ROIAlignRotated"
    _C.MODEL.ROI_RECOGNIZER_HEAD.NORM = "BN"
    _C.MODEL.ROI_RECOGNIZER_HEAD.CHARACTER_SET = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&''()*+,-./:;<=>?@[\]^_`{|}~ '
    _C.MODEL.ROI_RECOGNIZER_HEAD.RECOGNIZER_HEAD.BACKBONE = CN()
    _C.MODEL.ROI_RECOGNIZER_HEAD.RECOGNIZER_HEAD.BACKBONE.NAME = "CNN_V1_2"
    _C.MODEL.ROI_RECOGNIZER_HEAD.POOLER_SAMPLING_RATIO = 0
    _C.MODEL.ROI_RECOGNIZER_HEAD.CONV_DIM = 256

    _C.MODEL.ROI_RECOGNIZER_HEAD.SAMPLING_RATIO = 0
    _C.MODEL.ROI_RECOGNIZER_HEAD.RECOGNIZER_HEAD.ENCODER = CN()
    _C.MODEL.ROI_RECOGNIZER_HEAD.RECOGNIZER_HEAD.ENCODER.NAME = "BiLSTMBlockV2"  # | TransformerEncoderBlock
    _C.MODEL.ROI_RECOGNIZER_HEAD.RECOGNIZER_HEAD.ENCODER.NUM_OF_LAYERS = 2
    _C.MODEL.ROI_RECOGNIZER_HEAD.RECOGNIZER_HEAD.ENCODER.HEIGHT_REDUCTION = "mean"  # "flatten" | "mean"
    _C.MODEL.ROI_RECOGNIZER_HEAD.RECOGNIZER_HEAD.ENCODER.N_HEAD = 8  # for TransformerEncoderBlock (multi-attention heads)

    _C.MODEL.ROI_RECOGNIZER_HEAD.RECOGNIZER_HEAD.DECODER = CN()
    _C.MODEL.ROI_RECOGNIZER_HEAD.RECOGNIZER_HEAD.DECODER.NAME = "ASTER_V2"
    _C.MODEL.ROI_RECOGNIZER_HEAD.RECOGNIZER_HEAD.DECODER.POS_ENC_HEIGHT_WIDTH = None

    _C.MODEL.ROI_MASK_HEAD.MASK_INFERENCE = False


def merge_from_dataset_config(cfg, dataset_config_path):
    _C = cfg
    # Parsing the dataset_config_path
    with open(dataset_config_path, 'r') as fp:
        dataset_config = yaml.safe_load(fp)
    # Updating the fields in the config
    _C.DATASETS.TRAIN = dataset_config.get('DATASETS', [])
    _C.DATASETS.TEST = dataset_config.get('VAL_DATASETS', [])
    _C.DATASETS.ROOT = dataset_config.get('ROOT', '.')
    _C.DATASETS.CONFIG = os.path.basename(dataset_config_path)